networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # Configuración de la base de datos
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWD}
      # Configuración del servidor
      - GITEA__server__ROOT_URL=${GITEA__server__ROOT_URL}
      - GITEA__server__SSH_DOMAIN=${GITEA__server__SSH_DOMAIN}
      - GITEA__server__DOMAIN=${GITEA__server__DOMAIN}
      - GITEA__server__HTTP_PORT=${GITEA__server__HTTP_PORT}
      - GITEA__server__SSH_PORT=${GITEA__server__SSH_PORT}
      # Configuración de registro - DESHABILITADO
      - GITEA__service__REGISTER_EMAIL_CONFIRM=${GITEA__service__REGISTER_EMAIL_CONFIRM}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA__service__DISABLE_REGISTRATION}
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=${GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION}
      # Configuración de seguridad
      - GITEA__security__INSTALL_LOCK=true
      # Configuración de seguridad
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA__service__REQUIRE_SIGNIN_VIEW}
      - GITEA__repository__DEFAULT_PRIVATE=${GITEA__repository__DEFAULT_PRIVATE}
      - GITEA__repository__ENABLE_PUSH_CREATE_USER=${GITEA__repository__ENABLE_PUSH_CREATE_USER}
      - GITEA__repository__ENABLE_PUSH_CREATE_ORG=${GITEA__repository__ENABLE_PUSH_CREATE_ORG}
      - GITEA__repository__DISABLE_HTTP_GIT=${GITEA__repository__DISABLE_HTTP_GIT}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    networks:
      - gitea
    depends_on:
      - server

  db-backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    volumes:
      - ./backups:/backups
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - gitea
    restart: always
